### PR TITLE
support older Elixir and OTP

### PR DESCRIPTION
**Pull request by ruslandoga**
For https://github.com/swoosh/swoosh/pull/870#issuecomment-1966323164

### CODE REVIEW

**Comment by ruslandoga** [comment]
Eh, it's a bit more difficult than I expected.

**Comment by princemaple** [comment]
Hmm, I had to extract that calculation into a variable for some binary parser.

Is it OTP or Elixir bound?

**Comment by ruslandoga** [comment]
It's kind of both. It was added one OTP version earlier than Elixir started supporting it. So technically it should work in OTP-23+ but Elixir only allows it in OTP-24+ :) I'll add some conditional compilation around `size(...)` and `:public_key.cacerts_load()` for older versions.

**Comment by princemaple** [comment]
Or we can just skip Mua tests for now on Elixir 1.13, in Swoosh. (with some ex_unit tag magic)

Elixir 1.17 will probably come out in a few months or half a year. I support 4 Elixir versions and 3 OTP versions.

**Pull request merged**
